ETNA.MVC/Models/DI/EntregaViewModel.cs
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;


namespace ETNA.MVC.Models.DI
{
    public class EntregaViewModel
    {
        [Key]
        [DisplayName("Codigo")]
        public int Codigo { get; set; }

        [Key]
        [DisplayName("Nro. de Entrega:")]
        public string Numero { get; set; }

        [DisplayName("Fecha Emisión:")]
        [DisplayFormat(DataFormatString = "{0:dd/MM/yyyy}", ApplyFormatInEditMode = true)]
        public DateTime FechaGeneracion { get; set; }

        [DisplayName("Fecha Entrega:")]
        [DisplayFormat(DataFormatString = "{0:dd/MM/yyyy}", ApplyFormatInEditMode = true)]
        public DateTime FechaEntrega { get; set; }

        [DisplayName("Cliente:")]
        public string Cliente { get; set; }

        [DisplayName("Zona Despacho:")]
        public string ZonaDespacho { get; set; }

        [DisplayName("Estado:")]
        public string EstadoEntrega { get; set; }

        public List<DetalleEntregaViewModel> ListaDetalle { get; set; }

      
    }
}

ETNA.MVC/Models/DI/ListaEntregaViewModel.cs
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace ETNA.MVC.Models.DI
{
    public class ListaEntregaViewModel
    {
        [Key]
        [DisplayName("Codigo")]
        public int Codigo { get; set; }

        [Key]
        [DisplayName("Nro. de Entrega")]
        public string Numero { get; set; }

        [DisplayName("Fecha Emisión")]
        [DisplayFormat(DataFormatString = "{0:dd/MM/yyyy}")]
        public DateTime FechaGeneracion { get; set; }

        [DisplayName("Fecha Entrega")]
        [DisplayFormat(DataFormatString = "{0:dd/MM/yyyy}")]
        public DateTime FechaEntrega { get; set; }

        [DisplayName("Cliente")]
        public string Cliente { get; set; }

        [DisplayName("Zona Despacho")]
        public string ZonaDespacho { get; set; }

        public int idEstadoEntrega { get; set; }

    }
}

ETNA.MVC/Controllers/DI/DistribucionController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace ETNA.MVC.Controllers.DI
{
    public class DistribucionController : Controller
    {
        //
        // GET: /Distribucion/

        public ActionResult Index()
        {
            return View();
        }

    }
}

ETNA.MVC/Controllers/DI/EntregaController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using ETNA.BL.DI;
using AutoMapper;
using ETNA.MVC.Models.DI;

namespace ETNA.MVC.Controllers.DI
{
    public class EntregaController : Controller
    {
        //
        // GET: /Entrega/

        public ActionResult Index()
        {
            //Invocamos al servicio
            var service = new GestorEntrega();

            
            var entregasDto = service.ObtenerEntregas(DateTime.Today, DateTime.Now,0,0);

            //Mapeamos el DTO a nuestro modelo (de forma automática o a mano, dependiendo de nuestra necesidad)
            var listaEntregas = Mapper.Map<List<ListaEntregaViewModel>>(entregasDto);

            //Obtenemos la lista de clientes
            var serviceClientes = new GestorCliente();
            var listaClientes = serviceClientes.ObtenerClientes();

            //Obtenemos la lista de estados de las entregas
            var listaEstadosEntrega = service.ObtenerEstadosEntrega();

            var model = new FiltradoEntregasViewModel();

            model.GenerarEntrega = false;

            if (listaEntregas != null && listaEntregas.Count() == 0)
            {
                model.GenerarEntrega = true;
               
            }

            model.ListaInicial = listaEntregas;
            model.FechaInicio = DateTime.Today;
            model.FechaFin = DateTime.Now;
            model.Clientes =
                listaClientes.Select(
                    x => new SelectListItem() { Text = x.Nombre, Value = x.Codigo.ToString() })
                    .OrderBy(s => s.Text);
            model.EstadosEntrega =
                listaEstadosEntrega.Select(
                    x => new SelectListItem() { Text = x.Descripcion, Value = x.Codigo.ToString() })
                    .OrderBy(s => s.Text);

            return View(model);
        }

        [HttpPost]
        public PartialViewResult Index(FiltradoEntregasViewModel model)
        {
            //Invocamos al servicio
            var service = new GestorEntrega();

            
            var entregasDto = service.ObtenerEntregas(             
                model.FechaInicio.GetValueOrDefault(), model.FechaFin.GetValueOrDefault().AddDays(1),
                String.IsNullOrEmpty(model.IdCliente) ? 0 : Convert.ToInt32(model.IdCliente),
                String.IsNullOrEmpty(model.IdEstadoEntrega) ? 0 : Convert.ToInt32(model.IdEstadoEntrega));

            //Mapeamos el DTO a nuestro modelo (de forma automática o a mano, dependiendo de nuestra necesidad)
            var listaEntregas= Mapper.Map<List<ListaEntregaViewModel>>(entregasDto);

            return PartialView("_ListaEntrega", listaEntregas);
        }

        public ActionResult VerEntrega(int id)
        {
            //Invocamos al servicio
            var service = new GestorEntrega();
            var entregaDto = service.ObtenerEntrega(id);

            //Mapeamos el DTO a nuestro modelo (de forma automática o a mano, dependiendo de nuestra necesidad)
            var entrega = Mapper.Map<EntregaViewModel>(entregaDto);

            var detallesDto = service.ObtenerEntregaDetalles(id);

            var listaDetalles = Mapper.Map<List<DetalleEntregaViewModel>>(detallesDto);

            entrega.ListaDetalle = listaDetalles;

            return View(entrega);
        }

        public ViewResult GenerarEntrega()
        {

            return View();
        }

        [HttpPost]
        public JsonResult ProcesarEntrega()
        {
            int message = 0;

            //Invocamos al servicio
            var service = new GestorEntrega();

            service.generarEntregasFactura(DateTime.Today, DateTime.Now);
            service.generarEntregasPedido(DateTime.Today, DateTime.Now);

            message = 1;

            return Json(new
            {
                Message = message
            }, JsonRequestBehavior.AllowGet);
        }

        public ActionResult ModificarEntrega(int id)
        {
            //Invocamos al servicio
            var service = new GestorEntrega();
            var entregaDto = service.ObtenerEntrega(id);

            //Mapeamos el DTO a nuestro modelo (de forma automática o a mano, dependiendo de nuestra necesidad)
            var entrega = Mapper.Map<EntregaViewModel>(entregaDto);

            var detallesDto = service.ObtenerEntregaDetalles(id);

            var listaDetalles = Mapper.Map<List<DetalleEntregaViewModel>>(detallesDto);

            entrega.ListaDetalle = listaDetalles;

            return View(entrega);
        }

        [HttpPost]
        public JsonResult ModificarEntrega(int id, DateTime fechaEntrega)
        {
            int message = 0;
            //Invocamos al servicio
            var service = new GestorEntrega();

            service.modificarEntrega(id, fechaEntrega);

            message = 1;

            return Json(new
            {
                Message = message
            }, JsonRequestBehavior.AllowGet);
        }

        public ActionResult EliminarEntrega(int id)
        {
            //Invocamos al servicio
            var service = new GestorEntrega();
            var entregaDto = service.ObtenerEntrega(id);

            //Mapeamos el DTO a nuestro modelo (de forma automática o a mano, dependiendo de nuestra necesidad)
            var entrega = Mapper.Map<EntregaViewModel>(entregaDto);

            var detallesDto = service.ObtenerEntregaDetalles(id);

            var listaDetalles = Mapper.Map<List<DetalleEntregaViewModel>>(detallesDto);

            entrega.ListaDetalle = listaDetalles;

            return View(entrega);
        }

        [HttpPost]
        public JsonResult DesactivarEntrega(int id)
        {
            int message = 0;
            //Invocamos al servicio
            var service = new GestorEntrega();

            service.eliminarEntrega(id);

            message = 1;

            return Json(new
            {
                Message = message
            }, JsonRequestBehavior.AllowGet);
        }

    }
}

ETNA.MVC/Views/Entrega/EliminarEntrega.cshtml
@model ETNA.MVC.Models.DI.EntregaViewModel

@{
    ViewBag.Title = "Detalle de Entrega (Modificar)";
}

<h2>Detalle de Entrega (Modificar)</h2>

<fieldset>
    <legend>EntregaViewModel</legend>
    @using (Html.BeginForm(null, null, FormMethod.Post, new { id = "filtradoForm" }))
    {

        <div class="editor-label">
            @Html.LabelFor(model => model.Numero)
        </div>
        <div class="editor-field">
            @Html.TextBoxFor(model => model.Numero, new { disabled = "disabled", @readonly = "readonly" })
        </div>
        <div class="editor-label">
            @Html.LabelFor(model => model.FechaEntrega)
        </div>
        <div class="editor-field">
            @Html.TextBoxFor(model => model.FechaEntrega, "{0:dd/MM/yyyy}", new { disabled = "disabled", @readonly = "readonly" })
        </div>
        <div class="editor-label">
            @Html.LabelFor(model => model.Cliente)
        </div>
        <div class="editor-field">
            @Html.TextBoxFor(model => model.Cliente, new { disabled = "disabled", @readonly = "readonly" })
        </div>
        <div class="editor-label">
            @Html.LabelFor(model => model.EstadoEntrega)
        </div>
        <div class="editor-field">
            @Html.TextBoxFor(model => model.EstadoEntrega, new { disabled = "disabled", @readonly = "readonly" })
        </div>


    }
</fieldset>


<div id="targetDiv">
    @Html.Partial("_ListaDetalle", Model.ListaDetalle)
</div>

<div class="editor-field" style="padding-top: 10px;">
    <input type="button" value="Eliminar" onclick="eliminar();" />
    <a href="@Url.Action("Index", "Entrega")">
        <input type="button" value="Cerrar" />
    </a>

</div>

@section Scripts {
    <script type="text/javascript">
     
        var eliminar = function () {

            var r = confirm("¿Desea eliminar la Entrega?");

            if (r == true)
            {

                var id = '@Model.Codigo';
               
                $.ajax({
                    type: "POST",
                    url: "@Url.Action("DesactivarEntrega", "Entrega")",
                    data: {id:id},
                cache: false,
                dataType: "json",
                success: function (data) {
                    if (data.Message == 1) {
                        window.location.href = '@Url.Action("Index", "Entrega")';
                    }
                    else {
                        alert('Error, no se pudo culminar el proceso');
                    }
                }
            });

        }

        };



    </script>
}

ETNA.MVC/Views/Entrega/GenerarEntrega.cshtml
@{
    ViewBag.Title = "Generar Entregas";
}

<h2>Generar Entregas</h2>

<fieldset>
    <legend>GenerarEntrega</legend>
    <div class="editor-label">
        ¿Generar las entregas para la fecha?
    </div>

    <div class="editor-label">
        <input type="radio" id="fechaHoy" name="fecha" value="hoy" checked /> Hoy
    </div>

    <div class="editor-label">
        <input type="radio" id="fechaEspecifica" name="fecha" value="fechaEspecifica" /> Fecha Especifica :
        <input type="text" id="fechaGeneracion" name="fechaGeneracion"/>
    </div>

    <div class="editor-field" style="padding-top: 10px;">
        <input type="button" value="Aceptar" onclick="aceptar();" />
        <a href="@Url.Action("Index", "Entrega")">
            <input type="button" value="Cancelar"/>
        </a>
</div>

</fieldset>

@section Scripts {
    <script type="text/javascript">
        $(document).ready(function () {

            $('#fechaGeneracion').datepicker({ dateFormat: "dd/mm/yy" });
           
        });

        var aceptar = function () {

            var r = confirm("¿Generar Entregas?");

            if (r == true)
            {

                $.ajax({
                    type: "POST",
                    url: "@Url.Action("ProcesarEntrega", "Entrega")",
                    data: {},
                cache: false,
                dataType: "json",
                success: function (data) {
                    if (data.Message == 1) {
                        alert('Entregas generadas satisfactoriamente.');
                        window.location.href = '@Url.Action("Index", "Entrega")';
                    }
                    else {  
                        alert('Error, no se pudo culminar el proceso');
                    }
                }
             });

            }
            
        };

    </script>
}

ETNA.MVC/Views/Entrega/Index.cshtml
@model ETNA.MVC.Models.DI.FiltradoEntregasViewModel

@{
    ViewBag.Title = "Entregas";
}

<h2>Entregas</h2>

<fieldset>
    <legend>FiltradoEntregasViewModel</legend>
    @using (Html.BeginForm(null, null, FormMethod.Post, new { id = "filtradoForm" }))
{

    <div class="editor-label"><h3>
    Fechas de Emisión</h3>
    <div class="editor-label">
        @Html.LabelFor(model => model.FechaInicio)
    </div>
    <div class="editor-field">
        @Html.EditorFor(model => model.FechaInicio)
    </div>
    <div class="editor-label">
        @Html.LabelFor(model => model.FechaFin)
    </div>
    <div class="editor-field">
        @Html.EditorFor(model => model.FechaFin)
    </div>
</div>
        <div class="editor-label">
            @Html.LabelFor(model => model.IdCliente)
        </div>
        <div class="editor-field">
            @Html.DropDownListFor(model => model.IdCliente, Model.Clientes, "Todos")
        </div>
        <div class="editor-label">
            @Html.LabelFor(model => model.IdEstadoEntrega)
        </div>
        <div class="editor-field">
            @Html.DropDownListFor(model => model.IdEstadoEntrega, Model.EstadosEntrega, "Todos")
        </div>
        <div class="editor-field" style="padding-top: 10px;">
            <input type="button" value="Buscar" onclick="filtrar();" />
        </div>
    }
</fieldset>


<div id="targetDiv">
    @Html.Partial("_ListaEntrega", Model.ListaInicial)
</div>

@if (Model.GenerarEntrega)
{
    <div class="editor-field" style="padding-top: 10px;">
        <a href="@Url.Action("GenerarEntrega", "Entrega")">
        <input type="button" value="Generar" />
        </a>
        <a href="@Url.Action("Index", "Distribucion")">
            <input type="button" value="Cerrar" />
        </a>

    </div>
}

@section Scripts {
    <script type="text/javascript">
        $(document).ready(function () {

            $('#FechaInicio').datepicker({ dateFormat: "dd/mm/yy" });
            $('#FechaFin').datepicker({ dateFormat: "dd/mm/yy" });

            var message = '@ViewBag.Message';
            if (message)
                toastr["success"](message);
        });

        var filtrar = function () {
            $.post('@Url.Action("Index")', $('#filtradoForm').serialize(), function (data) {

                $('#targetDiv').html(data);

            }).error(function () {
                alert('there was an error');
            });
        };


    </script>
}

ETNA.MVC/Views/Entrega/ModificarEntrega.cshtml
@model ETNA.MVC.Models.DI.EntregaViewModel

@{
    ViewBag.Title = "Detalle de Entrega (Modificar)";
}

<h2>Detalle de Entrega (Modificar)</h2>

<fieldset>
    <legend>EntregaViewModel</legend>
    @using (Html.BeginForm(null, null, FormMethod.Post, new { id = "filtradoForm" }))
    {

        <div class="editor-label">
            @Html.LabelFor(model => model.Numero)
        </div>
        <div class="editor-field">
            @Html.TextBoxFor(model => model.Numero, new { disabled = "disabled", @readonly = "readonly" })
        </div>
        <div class="editor-label">
            @Html.LabelFor(model => model.FechaEntrega)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.FechaEntrega)
        </div>
        <div class="editor-label">
            @Html.LabelFor(model => model.Cliente)
        </div>
        <div class="editor-field">
            @Html.TextBoxFor(model => model.Cliente, new { disabled = "disabled", @readonly = "readonly" })
        </div>
        <div class="editor-label">
            @Html.LabelFor(model => model.EstadoEntrega)
        </div>
        <div class="editor-field">
            @Html.TextBoxFor(model => model.EstadoEntrega, new { disabled = "disabled", @readonly = "readonly" })
        </div>


    }
</fieldset>


<div id="targetDiv">
    @Html.Partial("_ListaDetalle", Model.ListaDetalle)
</div>

<div class="editor-field" style="padding-top: 10px;">
    <input type="button" value="Aceptar" onclick="modificar();" />
    <a href="@Url.Action("Index", "Entrega")">
        <input type="button" value="Cerrar" />
    </a>

</div>

@section Scripts {
    <script type="text/javascript">
        $(document).ready(function () {

            $('#FechaEntrega').datepicker({ dateFormat: "dd/mm/yy" });
           
        });

        var modificar = function () {

            var r = confirm("¿Desea confirmar los cambios?");

            if (r == true)
            {

                var id = '@Model.Codigo';
                var fechaEntrega = $('#FechaEntrega').val();
                
                $.ajax({
                    type: "POST",
                    url: "@Url.Action("ModificarEntrega", "Entrega")",
                    data: {id:id,fechaEntrega:fechaEntrega},
                cache: false,
                dataType: "json",
                success: function (data) {
                    if (data.Message == 1) {
                        window.location.href = '@Url.Action("Index", "Entrega")';
                    }
                    else {
                        alert('Error, no se pudo culminar el proceso');
                    }
                }
            });

        }
            
        };

        

    </script>
}

ETNA.MVC/Views/Entrega/VerEntrega.cshtml
@model ETNA.MVC.Models.DI.EntregaViewModel

@{
    ViewBag.Title = "Detalle de Entrega (Consultar)";
}

<h2>Detalle de Entrega (Consultar)</h2>

<fieldset>
    <legend>EntregaViewModel</legend>
    @using (Html.BeginForm(null, null, FormMethod.Post, new { id = "filtradoForm" }))
    {

        <div class="editor-label">
            @Html.LabelFor(model => model.Numero)
        </div>
        <div class="editor-field">
            @Html.TextBoxFor(model => model.Numero, new { disabled = "disabled", @readonly = "readonly" })
        </div>
        <div class="editor-label">
            @Html.LabelFor(model => model.FechaEntrega)
        </div>
        <div class="editor-field">
            @Html.TextBoxFor(model => model.FechaEntrega, "{0:dd/MM/yyyy}", new { disabled = "disabled", @readonly = "readonly" })
        </div>
        <div class="editor-label">
            @Html.LabelFor(model => model.Cliente)
        </div>
        <div class="editor-field">
            @Html.TextBoxFor(model => model.Cliente, new { disabled = "disabled", @readonly = "readonly" })
        </div>
        <div class="editor-label">
            @Html.LabelFor(model => model.EstadoEntrega)
        </div>
        <div class="editor-field">
            @Html.TextBoxFor(model => model.EstadoEntrega, new { disabled = "disabled", @readonly = "readonly" })
        </div>
       
       
    }
</fieldset>


<div id="targetDiv">
    @Html.Partial("_ListaDetalle", Model.ListaDetalle)
</div>

<div class="editor-field" style="padding-top: 10px;">
    <a href="@Url.Action("Index", "Entrega")">
        <input type="button" value="Cerrar" />
    </a>

</div>

ETNA.MVC/Views/Entrega/_ListaDetalle.cshtml
@model IEnumerable<ETNA.MVC.Models.DI.DetalleEntregaViewModel>
<table class="table table-striped">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.NroItem)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.NombreProducto)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.CantidadEntregaProg)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.CantidadEntregada)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.CantidadRechazada)
        </th>
        
    </tr>

    @foreach (var item in Model)
    {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.NroItem)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.NombreProducto)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.CantidadEntregaProg)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.CantidadEntregada)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.CantidadRechazada)
            </td>

        </tr>
    }
</table>

ETNA.MVC/Views/Entrega/_ListaEntrega.cshtml
@model IEnumerable<ETNA.MVC.Models.DI.ListaEntregaViewModel>
<table class="table table-striped">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.Numero)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.FechaGeneracion)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.FechaEntrega)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Cliente)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.ZonaDespacho)
        </th>
        <th></th>
        <th></th>
        <th></th>
    </tr>

    @if (Model.Count() > 0)
    {
          foreach (var item in Model)
        {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Numero)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.FechaGeneracion)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.FechaEntrega)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Cliente)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.ZonaDespacho)
            </td>
            <td>
                @Html.ActionLink("Ver", "VerEntrega", new { id = item.Codigo})
            </td>
            <td>
                @if (item.idEstadoEntrega != 4)
                { 
                     @Html.ActionLink("Modificar", "ModificarEntrega", new { id = item.Codigo })
                }
               
            </td>
            <td>
                @if (item.idEstadoEntrega != 4)
                {
                    @Html.ActionLink("Eliminar", "EliminarEntrega", new { id = item.Codigo })
                }
            </td>
        </tr>
        }
    }
    else
    {
         <tr>
             <td>
                 No se encontraron datos con los criterios seleccionados
             </td>
             </tr>
       

    }

  
</table>