ETNA.MVC/Models/LO/ListaSolicitudSalidaViewModel.cs
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace ETNA.MVC.Models.LO
{
    public class ListaSolicitudSalidaViewModel
    {
        [Key]
        [DisplayName("Código solicitud")]
        public int Id { get; set; }

        [DisplayName("Fecha Elaboración")]
        [DisplayFormat(DataFormatString = "{0:dd/MM/yyyy}")]
        public DateTime FechaElaboracion { get; set; }

        [DisplayName("Tipo de Salida")]
        public string TipoSalida { get; set; }

        [DisplayName("Estado")]
        public string Estado { get; set; }

        [DisplayName("Elaborada por")]
        public string NombreEmpleado { get; set; }

        [DisplayName("Direccion Entrega")]
        public string DireccionEntrega { get; set; }

        [DisplayName("Razon Social Destinatario")]
        public string RazonSocialDestinatario { get; set; }
    }
}

ETNA.MVC/Controllers/LO/GuiaSalidaController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Web.Routing;
using ETNA.BL.LO;
using ETNA.Common;
using ETNA.MVC.Models;
using ETNA.MVC.Models.LO;
using WebMatrix.WebData;
using AutoMapper;

namespace ETNA.MVC.Controllers.LO
{
    public class GuiaSalidaController : Controller
    {

        //TODO 
        // 1. Agregar el estado a los campos de la lista
        // 2. Validaciones de error
        // 3. Reconocer si es parcial o completa para poder el estado que corresponda

        public ActionResult Almacenes()
        {
            //Invocamos al servicio
            var service = new GestorAlmacenes();

            //Como código de empleado le pasamos el current user id (es importante que coincida con el empleado id)
            var almacenesDto = service.ObtenerAlmacenesPorEmpleado(WebSecurity.CurrentUserId);

            if (almacenesDto.Any())
            {
                //Si el usuario solo tiene un almacén asignado, obviamos este paso
                if (almacenesDto.Count() == 1)
                {
                    return RedirectToAction("Solicitudes", new { id = almacenesDto[0].Id });
                }

                //Mapeamos el DTO a nuestro modelo (de forma automática o a mano, dependiendo de nuestra necesidad)
                var model = Mapper.Map<List<AlmacenViewModel>>(almacenesDto);
                return View(model);
            }

            @ViewBag.Message = "El usuario no cuenta con ningún almacén asociado.";
            return View("Error");
        }

        public ActionResult Solicitudes(int id)
        {
            //Buscamos algún mensaje de éxito (si venimos de dar de alta una guía de salida)
            if (TempData.ContainsKey("Message"))
                @ViewBag.Message = TempData["Message"];

            //Invocamos al servicio
            var service = new GestorSolicitudesSalida();

            //Como código de empleado le pasamos el current user id (es importante que coincida con el empleado id)
            var solicitudesDto = service.ObtenerSolicitudesSalida(0, (int)Enums.EstadoSolicitudSalida.Aprobada,
                DateTime.MinValue, DateTime.MinValue, 0, 0, "Av. Benavides", "Almacenes SA");

            //Mapeamos el DTO a nuestro modelo (de forma automática o a mano, dependiendo de nuestra necesidad)
            var listaSolicitudes = Mapper.Map<List<ListaSolicitudSalidaViewModel>>(solicitudesDto);

            //Obtenemos la lista de empleados
            var serviceEmpleados = new GestorEmpleados();
            var listaEmpleados = serviceEmpleados.ObtenerEmpleados();

            var model = new FiltradoSolicitudesSalidaViewModel();
            model.ListaInicial = listaSolicitudes;
            model.Empleados =
                listaEmpleados.Select(
                    x => new SelectListItem() { Text = x.Apellidos + ", " + x.Nombres, Value = x.Id.ToString() })
                    .OrderBy(s => s.Text);
            return View(model);
        }

        [HttpPost]
        public PartialViewResult Solicitudes(FiltradoSolicitudesSalidaViewModel model)
        {
            //Invocamos al servicio
            var service = new GestorSolicitudesSalida();

            //Como código de empleado le pasamos el current user id (es importante que coincida con el empleado id)
            var solicitudesDto = service.ObtenerSolicitudesSalida(model.IdSolicitud.GetValueOrDefault(),
                (int)Enums.EstadoSolicitudSalida.Aprobada,
                model.FechaInicio.GetValueOrDefault(), model.FechaFin.GetValueOrDefault(),
                String.IsNullOrEmpty(model.IdEmpleado) ? 0 : Convert.ToInt32(model.IdEmpleado),
                String.IsNullOrEmpty(model.TipoSalida) ? 0 : Convert.ToInt32(model.TipoSalida),
                model.DireccionEntrega, model.RazonSocial);

            //Mapeamos el DTO a nuestro modelo (de forma automática o a mano, dependiendo de nuestra necesidad)
            var listaSolicitudes = Mapper.Map<List<ListaSolicitudSalidaViewModel>>(solicitudesDto);

            return PartialView("_ListaSolicitudSalida", listaSolicitudes);
        }

        public ActionResult Atender(int id, int idAlmacen)
        {
            @ViewBag.IdSolicitud = id;
            @ViewBag.IdAlmacen = idAlmacen;
            TempData["Message"] = "";

            //Invocamos al servicio
            var service = new GestorSolicitudesSalida();

            //Como código de empleado le pasamos el current user id (es importante que coincida con el empleado id)
            var solicitudesDto = service.ObtenerSolicitudSalida(id);

            //Mapeamos el DTO a nuestro modelo (de forma automática o a mano, dependiendo de nuestra necesidad)
            var model = Mapper.Map<SolicitudSalidaViewModel>(solicitudesDto);
            return View(model);
        }

        [HttpPost]
        public ActionResult Atender(AltaGuiaSalidaModel model)
        {
            //Invocamos al servicio
            //var service = new GestorGuiasSalida();
            //Mapper.CreateMap<ProductoGuiaSalidaViewModel, ProductoDto>();
            //var productosDto = Mapper.Map<ProductoDto[]>(model.Productos);
            //var success = service.GenerarGuiaSalidaParcial(model.IdSolicitud, model.IdAlmacen, WebSecurity.CurrentUserId,
            //    productosDto);

            //if (success)
            //{
            //    TempData["Message"] =
            //        String.Format("Se generó correctamente la guía de salida para la solicitud {0}", model.IdSolicitud);
            //}

            return Json(true); //RedirectToAction("Solicitudes", new { id = model.IdAlmacen });
        }

        // GET: /GuiaSalida/Details/5

        public ActionResult Details(int id)
        {
            return View();
        }

        //
        // GET: /GuiaSalida/Create

        public ActionResult Create()
        {
            return View();
        }

        //
        // POST: /GuiaSalida/Create

        [HttpPost]
        public ActionResult Create(FormCollection collection)
        {
            try
            {
                // TODO: Add insert logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        //
        // GET: /GuiaSalida/Edit/5

        public ActionResult Edit(int id)
        {
            return View();
        }

        //
        // POST: /GuiaSalida/Edit/5

        [HttpPost]
        public ActionResult Edit(int id, FormCollection collection)
        {
            try
            {
                // TODO: Add update logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        //
        // GET: /GuiaSalida/Delete/5

        public ActionResult Delete(int id)
        {
            return View();
        }

        //
        // POST: /GuiaSalida/Delete/5

        [HttpPost]
        public ActionResult Delete(int id, FormCollection collection)
        {
            try
            {
                // TODO: Add delete logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }
    }
}

ETNA.MVC/Views/GuiaSalida/Almacenes.cshtml
@model IEnumerable<ETNA.MVC.Models.LO.AlmacenViewModel>

@{
    ViewBag.Title = "Selección de Almacén";
}

<h2>Selección de Almacén</h2>

<table class="table table-striped">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.Id)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Nombre)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Direccion)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.Id)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Nombre)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Direccion)
        </td>
        <td>
            @Html.ActionLink("Seleccionar", "Solicitudes", new { id=item.Id }) 
        </td>
    </tr>
}

</table>

ETNA.MVC/Views/GuiaSalida/Atender.cshtml
@model ETNA.MVC.Models.LO.SolicitudSalidaViewModel

@{
    ViewBag.Title = "Atender solicitud de Salida";
}

<h2>Atender Solicitud de Salida</h2>

<fieldset>
    <legend>SolicitudSalidaViewModel</legend>

    <div class="display-label">
        @Html.DisplayNameFor(model => model.FechaElaboracion)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.FechaElaboracion)
    </div>

    <div class="display-label">
        @Html.DisplayNameFor(model => model.TipoSalida)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.TipoSalida)
    </div>

    <div class="display-label">
        @Html.DisplayNameFor(model => model.NombreEmpleado)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.NombreEmpleado)
    </div>
    @using (Html.BeginForm(null, null, FormMethod.Post, new { id = "guiasalidaform" }))
    {
        <div class="display-label">
            @Html.DisplayName("Productos")
        </div>
        <table class="table table-striped">
            <tr>
                <th>
                    @Html.DisplayName("Código de Producto")
                </th>
                <th>
                    @Html.DisplayName("Nombre")
                </th>
                <th>
                    @Html.DisplayName("Cantidad Inicial")
                </th>
                <th>
                    @Html.DisplayName("Cantidad Restante")
                </th>
                <th>
                    @Html.DisplayName("Cantidad Saliente")
                </th>
                <th></th>
            </tr>

            @foreach (var item in Model.Detalle)
            {
                <tr>
                    <td>
                        @Html.Hidden("IdProducto", item.Id)
                        @Html.DisplayFor(modelItem => item.Id)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.NombreProducto)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Cantidad)
                    </td>
                    <td>
                        @Html.Hidden("CantidadFinal", item.CantidadFinal)
                        @Html.DisplayFor(modelItem => item.CantidadFinal)
                    </td>
                    <td>
                        @Html.EditorFor(modelItem => item.CantidadSaliente, "", "cantidadSaliente")
                    </td>
                    <td></td>
                </tr>
            }
        </table>
        
        @Html.Hidden("IdSolicitud", (int)ViewBag.IdSolicitud)
        @Html.Hidden("IdAlmacen", (int)ViewBag.IdAlmacen)
        @Html.Hidden("Observaciones", "")
        @Html.Hidden("Rechazar", false)
    
        <input type="button" value="Cancelar" onclick="cancelar();" />
        <input type="button" value="Generar Guía" onclick="confirmarCreacion()" />
    }
</fieldset>
@section Scripts{
    <script type="text/javascript">

        $.postify = function(value) {
            var result = {};

            var buildResult = function(object, prefix) {
                for (var key in object) {

                    var postKey = isFinite(key)
                        ? (prefix != "" ? prefix : "") + "[" + key + "]"
                        : (prefix != "" ? prefix + "." : "") + key;

                    switch (typeof (object[key])) {
                    case "number":
                    case "string":
                    case "boolean":
                        result[postKey] = object[key];
                        break;

                    case "object":
                        if (object[key].toUTCString)
                            result[postKey] = object[key].toUTCString().replace("UTC", "GMT");
                        else {
                            buildResult(object[key], postKey != "" ? postKey : key);
                        }
                    }
                }
            };

            buildResult(value, "");

            return result;
        };

        var generarGuia = function() {

            var postdata = {};
            postdata.IdSolicitud = $('#IdSolicitud').val();
            postdata.IdAlmacen = $('#IdAlmacen').val();
            postdata.Productos = [];

            var idProductos = [];
            $('[name="IdProducto"]').each(function() {
                idProductos.push(this.value);
            });

            var cantidades = [];
            $('[name="cantidadSaliente"]').each(function() {
                cantidades.push(this.value);
            });

            var cantidadesFinales = [];
            $('[name="CantidadFinal"]').each(function () {
                cantidadesFinales.push(this.value);
            });

            for (var i = 0; i < idProductos.length; i++) {

                var cantidadesUnit = parseInt(cantidades[i]);
                var cantidadesFinalesUnit = parseInt(cantidadesFinales[i]);

                // Si cantidad no es un número

                var patron = /^\d*$/;

                if (patron.test(cantidadesUnit)) {
                    null;
                }
                else
                {
                    toastr["error"]('Por favor corrija las cantidades ingresadas. Deben ser números y no inferiores a cero.');
                    return false;
                }

                // Si cantidad < 0
                if (cantidadesUnit < 0) {
                    toastr["error"]('No se pueden atender atender cantidades inferiores a cero.');
                    return false;
                }
                // Si cantidad > cantidad restante
                if (cantidadesFinalesUnit < cantidadesUnit) {
                    toastr["error"]('No se pueden atender cantidades mayores que las restantes.');
                    return false;
                }

                postdata.Productos.push({ IdProducto: idProductos[i], CantidadSaliente: cantidades[i] });
            }


            $.post('@Url.Action("Atender")', $.postify(postdata), function(data) {
                var url = '@Url.Action("Solicitudes", new {id = ViewBag.IdAlmacen})';
                window.location = url;
            }).error(function() {
                alert('there was an error');
            });
        };

        var confirmarCreacion = function() {
            bootbox.dialog({
                message: "¿Está seguro de querer generar la guía de salida?",
                title: "Confirmación",
                buttons: {
                    cancel: {
                        label: "Cancelar",
                        callback: function() {
                            // Don't do anything
                        }
                    },
                    ok: {
                        label: "Aceptar",
                        callback: function() {
                            generarGuia();
                        }
                    }
                }
            });
        };

        var solicitarObservaciones = function() {
            bootbox.prompt("Por favor, ingrese las observaciones correspondientes.", function(result) {
                if (result == null) {
                    //Presionaron Cancel
                    return true;
                } else {
                    //Presionaron OK
                    if (result.trim() === '') {
                        //No metieron las observaciones
                        toastr["error"]('Las observaciones son un campo obligatorio.');
                        return false;
                    } else {
                        //Solicitamos el rechazo
                        $('#Observaciones').val(result);
                        $('#Rechazar').val(true);
                        $('#guiaentradaform').submit();
                        return true;
                    }
                }
            });
        };

        var cancelar = function() {
            var url = '@Url.Action("Solicitudes", "GuiaSalida", new {id = (int) ViewBag.IdAlmacen})';
            window.location.href = url;
        };


    </script>
}

ETNA.MVC/Views/GuiaSalida/Solicitudes.cshtml
@model ETNA.MVC.Models.LO.FiltradoSolicitudesSalidaViewModel

@{
    ViewBag.Title = "Solicitudes";
}

<h2>Solicitudes de Salida Aprobadas</h2>

<fieldset>
    <legend>FiltradoSolicitudesSalidaViewModel</legend>
    @using (Html.BeginForm(null, null, FormMethod.Post, new {id = "filtradoForm"}))
    {
        <div class="editor-label">
            @Html.LabelFor(model => model.IdSolicitud)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.IdSolicitud)
        </div>
        <div class="editor-label">
            @Html.LabelFor(model => model.FechaInicio)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.FechaInicio)
        </div>
        <div class="editor-label">
            @Html.LabelFor(model => model.FechaFin)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.FechaFin)
        </div>
        <div class="editor-label">
            @Html.LabelFor(model => model.TipoSalida)
        </div>
        <div class="editor-field">
            @Html.DropDownListFor(model => model.TipoSalida, Model.TiposSalida, "Seleccione un tipo de salida")
        </div>
        <div class="editor-label">
            @Html.LabelFor(model => model.IdEmpleado)
        </div>
        <div class="editor-field">
            @Html.DropDownListFor(model => model.IdEmpleado, Model.Empleados, "Seleccione un empleado")
        </div>
        <div class="editor-field" style="padding-top: 10px;">
            <input type="button" value="Filtrar" onclick=" filtrar(); " />
        </div>
    }
</fieldset>
    

<div id="targetDiv">
    @Html.Partial("_ListaSolicitudSalida", Model.ListaInicial)
</div>

@section Scripts {
    <script type="text/javascript">
        $(document).ready(function () {

            $('#FechaInicio').datepicker({ dateFormat: "dd/mm/yy" });
            $('#FechaFin').datepicker({ dateFormat: "dd/mm/yy" });

            var message = '@ViewBag.Message';
            if (message)
                toastr["success"](message);
        });

        var filtrar = function () {
            $.post('@Url.Action("Solicitudes")', $('#filtradoForm').serialize(), function (data) {

                $('#targetDiv').html(data);

            }).error(function () {
                alert('there was an error');
            });
        };
    </script>
}

ETNA.MVC/Views/GuiaSalida/_ListaSolicitudSalida.cshtml
@model IEnumerable<ETNA.MVC.Models.LO.ListaSolicitudSalidaViewModel>
<table class="table table-striped">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.Id)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.FechaElaboracion)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.TipoSalida)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.NombreEmpleado)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Estado)
        </th>
        <th></th>
    </tr>

    @foreach (var item in Model)
    {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Id)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.FechaElaboracion)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.TipoSalida)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.NombreEmpleado)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Estado)
            </td>
            <td>
                @Html.ActionLink("Atender", "Atender", new { id = item.Id, idAlmacen = ViewContext.RouteData.Values["id"]  })
            </td>
        </tr>
    }
</table>