ETNA.MVC/Models/LO/ListaSolicitudEntradaViewModel.cs
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace ETNA.MVC.Models.LO
{
    public class ListaSolicitudEntradaViewModel
    {
        [Key]
        [DisplayName("Código solicitud")]
        public int Id { get; set; }

        [DisplayName("Fecha Elaboración")]
        [DisplayFormat(DataFormatString = "{0:dd/MM/yyyy}")]
        public DateTime FechaElaboracion { get; set; }

        [DisplayName("Tipo de Entrada")]
        public string TipoEntrada { get; set; }

        [DisplayName("Elaborada por")]
        public string NombreEmpleado { get; set; }
    }
}

ETNA.MVC/Controllers/LO/GuiaEntradaController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Web.Routing;
using ETNA.BL.LO;
using ETNA.Common;
using ETNA.MVC.Models.LO;
using WebMatrix.WebData;
using AutoMapper;

namespace ETNA.MVC.Controllers.LO
{
    public class GuiaEntradaController : Controller
    {
        //
        // GET: /GuiaEntrada/
        // Lista de almacenes disponibles para el usuario
        public ActionResult Almacenes()
        {
            //Invocamos al servicio
            var service = new GestorAlmacenes();

            //Como código de empleado le pasamos el current user id (es importante que coincida con el empleado id)
            var almacenesDto = service.ObtenerAlmacenesPorEmpleado(WebSecurity.CurrentUserId);

            if (almacenesDto.Any())
            {
                //Si el usuario solo tiene un almacén asignado, obviamos este paso
                if (almacenesDto.Count() == 1)
                {
                    return RedirectToAction("Solicitudes", new { id = almacenesDto[0].Id });
                }

                //Mapeamos el DTO a nuestro modelo (de forma automática o a mano, dependiendo de nuestra necesidad)
                var model = Mapper.Map<List<AlmacenViewModel>>(almacenesDto);
                return View(model);
            }

            @ViewBag.Message = "El usuario no cuenta con ningún almacén asociado.";
            return View("Error");
        }

        //
        // GET: /GuiaEntrada/Solicitudes/5
        // Lista de solicitudes aprobadas listas para hacer una guía de entrada
        public ActionResult Solicitudes(int id)
        {
            //Buscamos algún mensaje de éxito (si venimos de dar de alta una guía de entrada)
            if (TempData.ContainsKey("Message"))
                @ViewBag.Message = TempData["Message"];

            //Invocamos al servicio
            var service = new GestorSolicitudesEntrada();
            
            //Como código de empleado le pasamos el current user id (es importante que coincida con el empleado id)
            var solicitudesDto = service.ObtenerSolicitudesEntrada(0, (int)Enums.EstadoSolicitudEntrada.Aprobada,
                DateTime.MinValue, DateTime.MinValue, 0, 0);

            //Mapeamos el DTO a nuestro modelo (de forma automática o a mano, dependiendo de nuestra necesidad)
            var listaSolicitudes = Mapper.Map<List<ListaSolicitudEntradaViewModel>>(solicitudesDto);

            //Obtenemos la lista de empleados
            var serviceEmpleados = new GestorEmpleados();
            var listaEmpleados = serviceEmpleados.ObtenerEmpleados();

            var model = new FiltradoSolicitudesEntradaViewModel();
            model.ListaInicial = listaSolicitudes;
            model.Empleados =
                listaEmpleados.Select(
                    x => new SelectListItem() {Text = x.Apellidos + ", " + x.Nombres, Value = x.Id.ToString()})
                    .OrderBy(s => s.Text);
            return View(model);
        }

        // POST /GuiaEntrada/Solicitudes/
        [HttpPost]
        public PartialViewResult Solicitudes(FiltradoSolicitudesEntradaViewModel model)
        {
            //Invocamos al servicio
            var service = new GestorSolicitudesEntrada();

            //Como código de empleado le pasamos el current user id (es importante que coincida con el empleado id)
            var solicitudesDto = service.ObtenerSolicitudesEntrada(model.IdSolicitud.GetValueOrDefault(),
                (int) Enums.EstadoSolicitudEntrada.Aprobada,
                model.FechaInicio.GetValueOrDefault(), model.FechaFin.GetValueOrDefault(),
                String.IsNullOrEmpty(model.IdEmpleado) ? 0 : Convert.ToInt32(model.IdEmpleado),
                String.IsNullOrEmpty(model.TipoEntrada) ? 0 : Convert.ToInt32(model.TipoEntrada));

            //Mapeamos el DTO a nuestro modelo (de forma automática o a mano, dependiendo de nuestra necesidad)
            var listaSolicitudes = Mapper.Map<List<ListaSolicitudEntradaViewModel>>(solicitudesDto);

            return PartialView("_ListaSolicitudEntrada",listaSolicitudes);
        }

        //
        // GET: /GuiaEntrada/Atender/5
        // Detalle de una solicitud de Entrada
        public ActionResult Atender(int id, int idAlmacen)
        {
            @ViewBag.IdSolicitud = id;
            @ViewBag.IdAlmacen = idAlmacen;
            TempData["Message"] = "";

            //Invocamos al servicio
            var service = new GestorSolicitudesEntrada();

            //Como código de empleado le pasamos el current user id (es importante que coincida con el empleado id)
            var solicitudesDto = service.ObtenerSolicitudEntrada(id);

            //Mapeamos el DTO a nuestro modelo (de forma automática o a mano, dependiendo de nuestra necesidad)
            var model = Mapper.Map<SolicitudEntradaViewModel>(solicitudesDto);
            return View(model);
        }

        //
        // POST: /GuiaEntrada/Atender/
        // Dar de alta una guía de entrada
        [HttpPost]
        public ActionResult Atender(AltaGuiaEntradaModel model)
        {
            //Invocamos al servicio
            var service = new GestorGuiasEntrada();

            if (model.Rechazar)
            {
                //Damos de alta la guía de entrada
                var success = service.RechazarGuiaEntrada(model.IdSolicitud, model.Observaciones);
                if (success)
                {
                    TempData["Message"] =
                        String.Format("Se rechazó correctamente la solicitud {0}", model.IdSolicitud);
                } 
            }
            else
            {
                //Damos de alta la guía de entrada
                var success = service.GenerarGuiaEntrada(model.IdSolicitud, model.IdSolicitud, WebSecurity.CurrentUserId);
                if (success)
                {
                    TempData["Message"] =
                        String.Format("Se generó correctamente la guía de entrada para la solicitud {0}",
                            model.IdSolicitud);
                }
            }

            return RedirectToAction("Solicitudes", new { id = model.IdAlmacen });
        }

        //
        // GET: /GuiaEntrada/Details/5

        public ActionResult Details(int id)
        {
            return View();
        }

        //
        // GET: /GuiaEntrada/Create

        public ActionResult Create()
        {
            return View();
        }

        //
        // POST: /GuiaEntrada/Create

        [HttpPost]
        public ActionResult Create(FormCollection collection)
        {
            try
            {
                // TODO: Add insert logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        //
        // GET: /GuiaEntrada/Edit/5

        public ActionResult Edit(int id)
        {
            return View();
        }

        //
        // POST: /GuiaEntrada/Edit/5

        [HttpPost]
        public ActionResult Edit(int id, FormCollection collection)
        {
            try
            {
                // TODO: Add update logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        //
        // GET: /GuiaEntrada/Delete/5

        public ActionResult Delete(int id)
        {
            return View();
        }

        //
        // POST: /GuiaEntrada/Delete/5

        [HttpPost]
        public ActionResult Delete(int id, FormCollection collection)
        {
            try
            {
                // TODO: Add delete logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }
    }
}

ETNA.MVC/Views/GuiaEntrada/Almacenes.cshtml
@model IEnumerable<ETNA.MVC.Models.LO.AlmacenViewModel>

@{
    ViewBag.Title = "Selección de Almacén";
}

<h2>Selección de Almacén</h2>

<table class="table table-striped">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.Id)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Nombre)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Direccion)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.Id)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Nombre)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Direccion)
        </td>
        <td>
            @Html.ActionLink("Seleccionar", "Solicitudes", new { id=item.Id }) 
        </td>
    </tr>
}

</table>

ETNA.MVC/Views/GuiaEntrada/Atender.cshtml
@model ETNA.MVC.Models.LO.SolicitudEntradaViewModel

@{
    ViewBag.Title = "Atender solicitud de Entrada";
}

<h2>Atender Solicitud de Entrada</h2>

<fieldset>
    <legend>SolicitudEntradaViewModel</legend>

    <div class="display-label">
        @Html.DisplayNameFor(model => model.FechaElaboracion)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.FechaElaboracion)
    </div>

    <div class="display-label">
        @Html.DisplayNameFor(model => model.TipoEntrada)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.TipoEntrada)
    </div>

    <div class="display-label">
        @Html.DisplayNameFor(model => model.NombreEmpleado)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.NombreEmpleado)
    </div>
    @using (Html.BeginForm(null, null, FormMethod.Post, new { id = "guiaentradaform" }))
    {
        <div class="display-label">
            @Html.DisplayName("Productos")
        </div>
        <table class="table table-striped">
            <tr>
                <th>
                    @Html.DisplayName("Código de Producto")
                </th>
                <th>
                    @Html.DisplayName("Nombre")
                </th>
                <th>
                    @Html.DisplayName("Cantidad")
                </th>
                <th></th>
            </tr>

            @foreach (var item in Model.Detalle)
            {
                <tr>
                    <td>
                        @Html.DisplayFor(modelItem => item.Id)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.NombreProducto)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Cantidad)
                    </td>
                    <td>
                    </td>
                </tr>
            }
        </table>
        
        @Html.Hidden("IdSolicitud", (int)ViewBag.IdSolicitud)
        @Html.Hidden("IdAlmacen", (int)ViewBag.IdAlmacen)
        @Html.Hidden("Observaciones", "")
        @Html.Hidden("Rechazar", false)
    
        <input type="button" value="Cancelar" onclick="cancelar();"/>
        <input type="button" value="Rechazar Solicitud" onclick="rechazarCreacion()" />
        <input type="button" value="Generar Guía" onclick="confirmarCreacion()" />
    }
</fieldset>
@section Scripts{
    <script type="text/javascript">
        var confirmarCreacion = function() {
            bootbox.dialog({
                message: "¿Está seguro de querer generar la guía de entrada?",
                title: "Confirmación",
                buttons: {
                    cancel: {
                        label: "Cancelar",
                        callback: function() {
                            // Don't do anything
                        }
                    },
                    ok: {
                        label: "Aceptar",
                        callback: function() {
                            $('#guiaentradaform').submit();
                        }
                    }
                }
            });
        };

        var rechazarCreacion = function() {
            bootbox.dialog({
                message: "¿Está seguro de querer rechazar la solicitud de entrada?",
                title: "Confirmación",
                buttons: {
                    cancel: {
                        label: "Cancelar",
                        callback: function() {
                            // Don't do anything
                        }
                    },
                    ok: {
                        label: "Aceptar",
                        callback: function() {
                            solicitarObservaciones();
                        }
                    }
                }
            });
        };

        var solicitarObservaciones = function() {
            bootbox.prompt("Por favor, ingrese las observaciones correspondientes.", function(result) {
                if (result == null) {
                    //Presionaron Cancel
                    return true;
                } else {
                    //Presionaron OK
                    if (result.trim() === '') {
                        //No metieron las observaciones
                        toastr["error"]('Las observaciones son un campo obligatorio.');
                        return false;
                    } else {
                        //Solicitamos el rechazo
                        $('#Observaciones').val(result);
                        $('#Rechazar').val(true);
                        $('#guiaentradaform').submit();
                        return true;
                    }
                }
            });
        };

        var cancelar = function() {
            var url = '@Url.Action("Solicitudes", "GuiaEntrada", new {id = (int)ViewBag.IdAlmacen })';
            window.location.href = url;
        };
    </script>
}

ETNA.MVC/Views/GuiaEntrada/Solicitudes.cshtml
@model ETNA.MVC.Models.LO.FiltradoSolicitudesEntradaViewModel

@{
    ViewBag.Title = "Solicitudes";
}

<h2>Solicitudes de Entrada Aprobadas</h2>

<fieldset>
    <legend>FiltradoSolicitudesEntradaViewModel</legend>
    @using (Html.BeginForm(null, null, FormMethod.Post, new { id = "filtradoForm" }))
    {
        <div class="editor-label">
            @Html.LabelFor(model => model.IdSolicitud)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.IdSolicitud)
        </div>
        <div class="editor-label">
            @Html.LabelFor(model => model.FechaInicio)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.FechaInicio)
        </div>
        <div class="editor-label">
            @Html.LabelFor(model => model.FechaFin)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.FechaFin)
        </div>
        <div class="editor-label">
            @Html.LabelFor(model => model.TipoEntrada)
        </div>
        <div class="editor-field">
            @Html.DropDownListFor(model => model.TipoEntrada, Model.TiposEntrada, "Seleccione un tipo de entrada")
        </div>
        
        <div class="editor-label">
            @Html.LabelFor(model => model.IdEmpleado)
        </div>
        <div class="editor-field">
            @Html.DropDownListFor(model => model.IdEmpleado, Model.Empleados, "Seleccione un empleado")
        </div>
        <div class="editor-field" style="padding-top: 10px;">
            <input type="button" value="Filtrar" onclick="filtrar();" />
        </div>
    }
</fieldset>


<div id="targetDiv">
    @Html.Partial("_ListaSolicitudEntrada", Model.ListaInicial)
</div>

@section Scripts {
    <script type="text/javascript">
        $(document).ready(function () {

            $('#FechaInicio').datepicker({ dateFormat: "dd/mm/yy" });
            $('#FechaFin').datepicker({ dateFormat: "dd/mm/yy" });

            var message = '@ViewBag.Message';
            if (message)
                toastr["success"](message);
        });

        var filtrar = function () {
            $.post('@Url.Action("Solicitudes")', $('#filtradoForm').serialize(), function (data) {

                $('#targetDiv').html(data);

            }).error(function () {
                alert('there was an error');
            });
        };
    </script>
}

ETNA.MVC/Views/GuiaEntrada/_ListaSolicitudEntrada.cshtml
@model IEnumerable<ETNA.MVC.Models.LO.ListaSolicitudEntradaViewModel>
<table class="table table-striped">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.Id)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.FechaElaboracion)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.TipoEntrada)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.NombreEmpleado)
        </th>
        <th></th>
    </tr>

    @foreach (var item in Model)
    {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Id)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.FechaElaboracion)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.TipoEntrada)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.NombreEmpleado)
            </td>
            <td>
                @Html.ActionLink("Atender", "Atender", new { id = item.Id, idAlmacen = ViewContext.RouteData.Values["id"] })
            </td>
        </tr>
    }
</table>