ETNA.MVC/Controllers/DI/DistribucionController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace ETNA.MVC.Controllers.DI
{
    public class DistribucionController : Controller
    {
        //
        // GET: /Distribucion/

        public ActionResult Index()
        {
            return View();
        }

    }
}

ETNA.MVC/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace ETNA.MVC.Controllers
{
    public class HomeController : Controller
    {
        //prueba diego git desde vs 2013
        public ActionResult Index()
        {
            ViewBag.Message = "Bienvenido a la aplicación baterías ETNA.";

            return View();
        }

        public ActionResult About()
        {
            ViewBag.Message = "Página de descripción de la aplicación.";

            return View();
        }

        public ActionResult Contact()
        {
            ViewBag.Message = "Página de contacto.";

            return View();
        }
    }
}

ETNA.MVC/Controllers/LO/LogisticaController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace ETNA.MVC.Controllers.LO
{
    public class LogisticaController : Controller
    {
        //
        // GET: /Logistica/

        public ActionResult Index()
        {
            return View();
        }

    }
}

ETNA.MVC/Views/Home/About.cshtml
@{
    ViewBag.Title = "Acerca de";
}

<hgroup class="title">
    <h1>@ViewBag.Title.</h1>
    <h2>@ViewBag.Message</h2>
</hgroup>

<article>
    <p>
        Use esta área para proporcionar información adicional.
    </p>

    <p>
        Use esta área para proporcionar información adicional.
    </p>

    <p>
        Use esta área para proporcionar información adicional.
    </p>
</article>

<aside>
    <h3>Al lado del título</h3>
    <p>
        Use esta área para proporcionar información adicional.
    </p>
    <ul>
        <li>@Html.ActionLink("Inicio", "Index", "Home")</li>
        <li>@Html.ActionLink("Acerca de", "About", "Home")</li>
        <li>@Html.ActionLink("Contacto", "Contact", "Home")</li>
    </ul>
</aside>

ETNA.MVC/Views/Home/Contact.cshtml
@{
    ViewBag.Title = "Contacto";
}

<hgroup class="title">
    <h1>@ViewBag.Title.</h1>
    <h2>@ViewBag.Message</h2>
</hgroup>

<section class="contact">
    <header>
        <h3>Teléfono</h3>
    </header>
    <p>
        <span class="label">Principal:</span>
        <span>425.555.0100</span>
    </p>
    <p>
        <span class="label">Fuera del horario laboral:</span>
        <span>425.555.0199</span>
    </p>
</section>

<section class="contact">
    <header>
        <h3>Correo electrónico</h3>
    </header>
    <p>
        <span class="label">Support:</span>
        <span><a href="mailto:Support@example.com">Support@example.com</a></span>
    </p>
    <p>
        <span class="label">Marketing:</span>
        <span><a href="mailto:Marketing@example.com">Marketing@example.com</a></span>
    </p>
    <p>
        <span class="label">General:</span>
        <span><a href="mailto:General@example.com">General@example.com</a></span>
    </p>
</section>

<section class="contact">
    <header>
        <h3>Dirección</h3>
    </header>
    <p>
        One Microsoft Way<br />
        Redmond, WA 98052-6399
    </p>
</section>

ETNA.MVC/Views/Home/Index.cshtml
@{
    ViewBag.Title = "Baterías ETNA";
}
@section featured {
    <section class="featured">
        <div class="content-wrapper">
            <hgroup class="title">
                <h1>@ViewBag.Title.</h1>
                <h2>@ViewBag.Message</h2>
            </hgroup>
            <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Morbi euismod suscipit erat. Phasellus semper, arcu nec fringilla auctor, libero sapien faucibus orci, egestas hendrerit libero ligula rhoncus felis. Sed id elit ipsum. Nam id purus nisi. Mauris a enim feugiat, ornare urna sed, finibus ipsum. Nullam interdum lectus vel velit lobortis malesuada. Proin convallis eu lectus vitae pellentesque. Proin pulvinar porta dui dapibus elementum. Nam faucibus pulvinar velit aliquam tincidunt. Ut laoreet odio non rutrum porttitor. Quisque ac leo ac arcu fringilla luctus. Donec hendrerit nisi sit amet ligula tempus, sed condimentum est blandit. Cras luctus mollis nibh eu sodales. Sed posuere, augue a venenatis consectetur, justo odio luctus tellus, non consectetur lorem mauris mollis neque. Donec vel gravida arcu. Vivamus non ornare ex, sit amet maximus augue.</p>
        </div>
    </section>
}
<h3>Le sugerimos lo siguiente:</h3>
<ol class="round">
    <li class="one">
        <h5>@Html.ActionLink("Fabricación", "Index", "Fabricacion")</h5>
        Lorem ipsum dolor sit amet, consectetur adipiscing elit. Morbi euismod suscipit erat. Phasellus semper, arcu nec fringilla auctor, libero sapien faucibus orci, egestas hendrerit libero ligula rhoncus felis. Sed id elit ipsum. Nam id purus nisi. Mauris a enim feugiat, ornare urna sed, finibus ipsum. Nullam interdum lectus vel velit lobortis malesuada. Proin convallis eu lectus vitae pellentesque. Proin pulvinar porta dui dapibus elementum. Nam faucibus pulvinar velit aliquam tincidunt. Ut laoreet odio non rutrum porttitor. Quisque ac leo ac arcu fringilla luctus. Donec hendrerit nisi sit amet ligula tempus, sed condimentum est blandit. Cras luctus mollis nibh eu sodales. Sed posuere, augue a venenatis consectetur, justo odio luctus tellus, non consectetur lorem mauris mollis neque. Donec vel gravida arcu. Vivamus non ornare ex, sit amet maximus augue.
        
    </li>

    <li class="two">
        <h5>@Html.ActionLink("Logística", "Index", "Logistica")</h5>
        Lorem ipsum dolor sit amet, consectetur adipiscing elit. Morbi euismod suscipit erat. Phasellus semper, arcu nec fringilla auctor, libero sapien faucibus orci, egestas hendrerit libero ligula rhoncus felis. Sed id elit ipsum. Nam id purus nisi. Mauris a enim feugiat, ornare urna sed, finibus ipsum. Nullam interdum lectus vel velit lobortis malesuada. Proin convallis eu lectus vitae pellentesque. Proin pulvinar porta dui dapibus elementum. Nam faucibus pulvinar velit aliquam tincidunt. Ut laoreet odio non rutrum porttitor. Quisque ac leo ac arcu fringilla luctus. Donec hendrerit nisi sit amet ligula tempus, sed condimentum est blandit. Cras luctus mollis nibh eu sodales. Sed posuere, augue a venenatis consectetur, justo odio luctus tellus, non consectetur lorem mauris mollis neque. Donec vel gravida arcu. Vivamus non ornare ex, sit amet maximus augue.
    </li>

    <li class="three">
        <h5>@Html.ActionLink("Distribución", "Index", "Distribucion")</h5>
        Lorem ipsum dolor sit amet, consectetur adipiscing elit. Morbi euismod suscipit erat. Phasellus semper, arcu nec fringilla auctor, libero sapien faucibus orci, egestas hendrerit libero ligula rhoncus felis. Sed id elit ipsum. Nam id purus nisi. Mauris a enim feugiat, ornare urna sed, finibus ipsum. Nullam interdum lectus vel velit lobortis malesuada. Proin convallis eu lectus vitae pellentesque. Proin pulvinar porta dui dapibus elementum. Nam faucibus pulvinar velit aliquam tincidunt. Ut laoreet odio non rutrum porttitor. Quisque ac leo ac arcu fringilla luctus. Donec hendrerit nisi sit amet ligula tempus, sed condimentum est blandit. Cras luctus mollis nibh eu sodales. Sed posuere, augue a venenatis consectetur, justo odio luctus tellus, non consectetur lorem mauris mollis neque. Donec vel gravida arcu. Vivamus non ornare ex, sit amet maximus augue.
    </li>
</ol>